In [1]:
import torch

In [2]:
# 1. Создайте случайный FloatTensor размера 3x4x5

# тензор процессора 3х4х5 float32, 
# заполненный случайными числами из нормального распределения N(0,1)
a = torch.randn((3,4,5), dtype=torch.float32, device='cpu') 

# тензор процессора 3х4х5 с мусором float32
b = torch.FloatTensor(3,4,5) 

# тензор процессора 3х4х5 с мусором float32
c = torch.empty(3,4,5, dtype=torch.float32, device='cpu') 
a, b, c

(tensor([[[-0.9487, -0.4330, -0.2377, -0.2733, -0.6286],
          [-0.0401, -1.0807, -1.0086, -1.0925, -0.7187],
          [-0.9946,  0.7539,  0.0850, -0.0937,  0.2070],
          [ 0.3235, -0.6705, -1.5097,  0.3129, -0.7813]],
 
         [[-1.3191, -0.1249,  0.2154,  0.3536,  0.9017],
          [ 0.7846, -0.2650, -1.5159,  1.7845,  1.9728],
          [-1.1248,  0.7515, -1.0131,  0.1800, -1.3098],
          [ 0.7468,  0.4031,  1.1055, -1.2941, -1.0970]],
 
         [[-1.0983, -0.3088,  0.3853, -0.9795, -1.4832],
          [-0.1075,  0.5149,  0.3423, -1.0807, -2.1456],
          [-1.3022, -0.5649,  0.1152, -0.6923, -0.2965],
          [-0.9189, -0.8957,  1.2016, -0.9114, -0.0995]]]),
 tensor([[[-7.7198e+00,  7.5670e-43, -7.6770e+00,  7.5670e-43, -7.7331e+00],
          [ 7.5670e-43, -7.7161e+00,  7.5670e-43, -4.8341e-02,  7.5670e-43],
          [-4.8341e-02,  7.5670e-43, -3.8530e+00,  7.5670e-43, -3.8530e+00],
          [ 7.5670e-43, -7.7238e+00,  7.5670e-43, -7.7238e+00,  7.5670e-43]]

In [3]:
# 2. Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [4]:
# 3. Приведите его к форме 6х10
a = a.reshape(6,10)
a

tensor([[-0.9487, -0.4330, -0.2377, -0.2733, -0.6286, -0.0401, -1.0807, -1.0086,
         -1.0925, -0.7187],
        [-0.9946,  0.7539,  0.0850, -0.0937,  0.2070,  0.3235, -0.6705, -1.5097,
          0.3129, -0.7813],
        [-1.3191, -0.1249,  0.2154,  0.3536,  0.9017,  0.7846, -0.2650, -1.5159,
          1.7845,  1.9728],
        [-1.1248,  0.7515, -1.0131,  0.1800, -1.3098,  0.7468,  0.4031,  1.1055,
         -1.2941, -1.0970],
        [-1.0983, -0.3088,  0.3853, -0.9795, -1.4832, -0.1075,  0.5149,  0.3423,
         -1.0807, -2.1456],
        [-1.3022, -0.5649,  0.1152, -0.6923, -0.2965, -0.9189, -0.8957,  1.2016,
         -0.9114, -0.0995]])

In [5]:
# 4. Создайте случайный IntTensor размера 10
b = torch.randint(0, 10, (10,), dtype=torch.int32, device='cpu')
b

tensor([5, 2, 2, 9, 8, 9, 8, 2, 8, 0], dtype=torch.int32)

In [6]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
c = a * b
print(c)

tensor([[ -4.7433,  -0.8660,  -0.4754,  -2.4596,  -5.0285,  -0.3607,  -8.6459,
          -2.0171,  -8.7402,  -0.0000],
        [ -4.9731,   1.5078,   0.1700,  -0.8432,   1.6558,   2.9117,  -5.3644,
          -3.0195,   2.5033,  -0.0000],
        [ -6.5955,  -0.2497,   0.4309,   3.1827,   7.2136,   7.0610,  -2.1199,
          -3.0318,  14.2757,   0.0000],
        [ -5.6239,   1.5030,  -2.0262,   1.6201, -10.4782,   6.7209,   3.2248,
           2.2111, -10.3529,  -0.0000],
        [ -5.4916,  -0.6177,   0.7705,  -8.8158, -11.8657,  -0.9675,   4.1192,
           0.6846,  -8.6456,  -0.0000],
        [ -6.5109,  -1.1298,   0.2304,  -6.2308,  -2.3718,  -8.2699,  -7.1654,
           2.4032,  -7.2915,  -0.0000]])


In [7]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
s = c.matmul(c.T)
s.shape
s

tensor([[ 210.1510,   45.4908, -115.6800,  130.7634,  146.4850,  182.8191],
        [  45.4908,   83.1257,  118.5808,  -19.1483,  -34.3284,   20.8895],
        [-115.6800,  118.5808,  373.2525, -148.4634, -218.0079, -148.1977],
        [ 130.7634,  -19.1483, -148.4634,  318.0522,  236.2462,   51.3239],
        [ 146.4850,  -34.3284, -218.0079,  236.2462,  342.7664,  162.8735],
        [ 182.8191,   20.8895, -148.1977,   51.3239,  162.8735,  266.8445]])

In [8]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)

x=torch.tensor(1.0, requires_grad=True) 
z=torch.tensor(0.5, requires_grad=True) 
t=torch.tensor(2.0, requires_grad=True)  
y=x**3+z-75*t
y.backward() 
x.grad, z.grad, t.grad




(tensor(3.), tensor(1.), tensor(-75.))

In [9]:
# 8. Создайте единичный тензор размера 5x6
once = torch.ones(5,6)
once

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [10]:
# 9. Переведите его в формат numpy
once = once.numpy()
once

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)